name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hey there, and welcome to our Open Source Community!

We're stoked to have you as a new contributor. Thanks for joining our project and taking that first step towards contributing. Your participation is crucial to our open source project's success.

Feel free to dive into our codebase, get to know our guidelines, and don't hesitate to ask questions if you need help. We're here to support you every step of the way.

Remember, every contribution counts, no matter how big or small. Your code, documentation, bug reports, and feedback are highly appreciated. Together, we can create some awesome software!

Once again, welcome to our community! We're pumped to see your contributions and can't wait to collaborate with you. Happy coding! 🎉

Best,
Dawson"


       pr-message: "Hey there, and congrats on your first pull request!

We're thrilled to see your contribution to our open source project. Thanks for taking the initiative to submit a pull request and help us make our software even better.

Our team will review your changes and provide feedback. Don't worry if you're new to pull requests or open source contributions – we're here to help and guide you along the way.

Your effort is truly appreciated, and we value your contribution, no matter the size. Keep up the great work, and we look forward to collaborating with you on more contributions in the future!

Thanks again for your pull request, and welcome to our community!

Best,

Dawson"
